tire_diameter: 6.24
loop_throttle: 0.025
landscape: yes
gyro_tolerance: 1
gyro_off: -12

gearbox:
    drive_shaft: A
    gear_selector: B

driving_motors:
    left: D
    right: C

sensors:
    left: E
    right: F

correctors:
    gyro_turn:
        p: 1.1
        i: 0
        d: -0.2

        # In deg/s:
        min_speed: 5
        max_speed: 90

    gyro_drive:
        p: 0.9
        i: 0.0005
        d: -1.2

    motors:
        driving_power:
            p: 50
            i: 0
            d: 5

        driving_differential:
            p: 30
            i: 0
            d: 4

        shaft_power:
            p: 2
            i: 0
            d: 1

        selector_power:
            p: 70
            i: 70
            d: 1

competition: no
debugging:
    no_autoscroll: yes
    initial_focus: 0
    require_battery_full: no
    display_errors: no
