debug_mode: on
tire_diameter: 6.5
loop_throttle: 0.025
landscape: yes
gyro_tolerance: 1
gyro_off: -11

gearbox:
    drive_shaft: A
    gear_selector: B

driving_motors:
    left: C
    right: D

sensors:
    left: E
    right: F

correctors:
    gyro_turn:
        p: 1.1
        i: 0
        d: -0.2

        # In deg/s:
        min_speed: 5
        max_speed: 90

    gyro_drive:
        p: 0.45
        i: 0.001
        d: -0.7

    motors:
        driving_power:
            p: 50
            i: 0
            d: 5

        driving_differential:
            p: 30
            i: 0
            d: 4

        shaft_power:
            p: 2
            i: 0
            d: 1

        selector_power:
            p: 70
            i: 70
            d: 1
