tire_diameter: 6.24
loop_throttle: 0.025
landscape: yes
gyro_tolerance: 1
gyro_off: 0

gearbox:
    drive_shaft: A
    gear_selector: B

    # "Dieses Problem ist softwaretechnisch zu l√∂sen" - danke
    offset: -7

driving_motors:
    left: D
    right: C

sensors:
    left: E
    right: F

correctors:
    gyro_turn:
        p: 1.6
        i: 0
        d: -1

        # In deg/s:
        min_speed: 5
        max_speed: 90

    gyro_drive:
        p: 1.1
        i: 0 #.001
        d: 0

competition: no
debugging:
    no_autoscroll: yes
    initial_focus: 6
    require_battery_full: no
    display_errors: no
