tire_diameter: 6.24
loop_throttle: 0.025
landscape: yes
gyro_tolerance: 1
gyro_off: -4

gearbox:
    drive_shaft: B
    gear_selector: A

    # "Dieses Problem ist softwaretechnisch zu l√∂sen" - danke
    offset: 90

driving_motors:
    left: C
    right: D

sensors:
    left: E
    right: F

correctors:
    gyro_turn:
        p: 1.6
        i: 0
        d: -1

        # In deg/s:
        min_speed: 5
        max_speed: 90

    gyro_drive:
        p: 1.3
        i: 0.001
        d: -1

competition: no
debugging:
    no_autoscroll: yes
    initial_focus: 0
    require_battery_full: no
    display_errors: no
