debug_mode: on
tire_diameter: 6.5
gyro_tolerance: 1
loop_throttle: 0.025
landscape: yes

gearbox:
    drive_shaft: A
    gear_selector: B

driving_motors:
    left: C
    right: D

sensors:
    left: E
    right: F

correctors:
    gyro_turn:
        p: 0.8
        i: 0
        d: -0.1

        # In deg/s:
        min_speed: 2
        max_speed: 90

    gyro_drive:
        p: 1.7
        i: 0
        d: -0.3
